#!/bin/bash
: <<\EOF
숨겨진 영역(path : */.*)과 숨겨진 파일(name : .*)은 대상에서 제외된다.
첫번째 인수에 'no'를 주면, 작업완료 알림을 출력하지 않는다.

작업내용:
uri incoding을 decoding
'+', '_'를 제거(스페이스 문자로 치환)
줄바꿈을 제거(스페이스 문자로 치환)
시작과 끝에서의 공백문자를 제거
파일의 확장자 앞의 공백문자를 제거
EOF

{
echo '=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+'
date

IFS='
'

#현재위치를 기억
home=`pwd`

#작업 대상이 될 위치들을 추출
:<<\EOF
if [ "$home" = "$HOME/Home/작업공간/보존 작업 중/정리완료" -o "$home" = "/media/ntfs_ssd/Homedir/작업공간/보존 작업 중/정리완료" ]
then
 temp=`find . ! \( -path '*/.*' -o -path "./정리완료" -prune \) -type d`
 echo -e "\n줄바꿈을 제거합니다."; find . ! \( -path '*/.*' -o -path "./정리완료" -prune \) -exec rename -v 's/\n/\ /g' "{}" \; #줄바꿈을 제거
else
EOF
temp=`find . ! \( -path '*/.*' -prune \) -type d`
echo -e "\n줄바꿈을 제거합니다."; find . ! \( -path '*/.*' -prune \) -exec rename -v 's/\n/\ /g' "{}" \; #줄바꿈을 제거
#fi

#역순으로 정렬
last=`echo "$temp" | fgrep -c ''`
countt=$last
for i in `seq $last`
do
 temp2=`echo "$temp2"; echo "$temp" | sed -n "${countt}p"`
 countt=`expr $countt - 1`
done

#파일 이름을 고침
echo -e "\n파일 이름을 고칩니다."; echo "작업위치 : $home";
for i in $temp2
do
 cd "$i" #작업 위치로 이동
 echo ''; echo "$i에서"
 for a in `ls`
 do
  f=$(echo "$a" | echo -e "$(sed 's/+/ /g; s/%/\\x/g')" | sed -r -e 's/\+/\ /g' -e 's/◆/\ /g' -e 's/_/\ /g' -e 's/^\s+//' -e 's/\s+$//') #공통 수정
  if [ -f "$a" ] #파일일 경우는 추가 수정
  then f=$(echo "$f" | sed -r -e 's/\s+\.([^\.\s]+)$/.\1/')
  fi
  if [ "$a" != "$f" -a -e "$f" ] #수정될 이름을 가진 대상이 존재하는지 확인
  then
   erro=$(echo "$erro"; echo "$i/$a") #에러 목록을 작성
  elif [ "$a" != "$f" -a ! -e "$f" ]
  then
   mv -Tv "$a" "$f" #이름을 수정
  fi
 done
 cd "$home" #초기 위치로 복귀
done

#작업 결과를 알림
if [ "$erro" ]
then
 for i in $erro
 do
  path=$(dirname "$i")
  name=$(basename "$i")
  erro_list=`echo -n "${erro_list} \"$name\" \"$path\""`
 done
 bash <<EOF
 zenity --list \
        --title "알림" \
        --text "수정될 이름을 가진 대상이 존재합니다!" \
        --height 400 \
        --column '이름' \
        --column '위치' $erro_list
EOF
else
 if [ "$1" != no ]
 then
  zenity --info --title '알림' --text '작업이 완료되었습니다.'
 fi
fi

echo ''
} 2>&1 | tee -a ~/"Home/.usersys/Log_nautilus-scripts/$(basename "$0").log"

exit
