#!/bin/bash

{
echo '=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+'
date

IFS='
'

#작업 대상이 될 위치들을 추출
temp=`find "$(pwd)" -not \( -type d -name ".*" -prune \) -type d`

#역순으로 정렬
last=`echo "$temp" | fgrep -c ''`
countt=$last
for i in `seq $last`
do
 temp2=`echo "$temp2"; echo "$temp" | sed -n "${countt}p"`
 countt=`expr $countt - 1`
done

#파일 이름을 고침
for i in `echo "$temp2" | sed '1d'`
do
 for a in `ls "$i"`
 do
  f=$(basename "$a" | iconv -c)
  mv -Tv "$i/$a" "$i/$f"
 done
done

zenity --info --title '알림' --text '작업이 완료되었습니다.'

echo ''
} 2>&1 | tee -a ~/"Home/.usersys/Log_nautilus-scripts/$(basename "$0").log"

exit
